### ISSUE TITLE
Debugging Server object extensions (SOEs) or Server object interceptors (SOIs) at IntelliJ IDE

### ISSUE THREAD

**Issue by AmirSarrafzadeh** [Esri/arcgis-enterprise-sdk-resources#17]
Dear Madam/Sir,

I hope all of you are doing well,

I have started to learn about SOE and SOI, I followed all the steps of ESRI (ArcGIS Enterprise SDK, Java Guide), and I somehow finished all the steps, but in the final step I could run the debug extensions in my IntelliJ IDE.

Thank you in advance for your time and kind consideration,

Have a nice day

**Comment by hanhansun** [comment]
To debug a Java SOE or SOI, you can follow the instructions here:
https://developers.arcgis.com/enterprise-sdk/guide/java/debug-extensions-dedicated-java/

The debugger must be attached to the running service process via remote debugging. Currently, SOE/SOI can't be debugged as a standalone application.
