### ISSUE TITLE
request a new feature

### ISSUE THREAD

**Issue by zhangvv** [Esri/arcgis-enterprise-sdk-resources#4]
When to support custom **mapping**? 
Because there are many special mapping requirements for government projects, it is necessary to handle the layout of mapping by yourself, such as dynamically drawing tables and inserting data.
We can easily realize the complex mapping  through ArcObject,[here](http://ghj.nanjing.gov.cn/pqgs/jsxmpqgs/201901/P020190102614769711089.jpg) is an example.

Thank you.

**Comment by hanhansun** [comment]
@zhangvv This is not on the plan. It's recommended to use [custom print service scripted with arcpy](https://pro.arcgis.com/en/pro-app/arcpy/mapping/web-map-printing-with-arcpy-mp.htm) to customize the layout of web map printing and [dynamic layer](https://developers.arcgis.com/rest/services-reference/dynamic-layer-table.htm#) to modify or insert the layers/tables to draw. This article (https://enterprise.arcgis.com/en/server/latest/develop/linux/alternatives-to-server-object-extensions.htm) explains how these two options can be alternatives to SOEs.
